# Generated by Django 2.2.7 on 2019-12-17 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driverkundliB2Bportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_reference_no', models.IntegerField()),
                ('driver_driver_name', models.CharField(default='', max_length=264)),
                ('driver_vehicle_type', models.CharField(blank=True, max_length=264)),
                ('vehicle_type_of_module', models.CharField(blank=True, max_length=264)),
                ('driver_joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_license_number', models.CharField(blank=True, max_length=264)),
                ('driver_aadhar_number', models.CharField(blank=True, default='', max_length=264)),
                ('driver_contact_number', models.CharField(blank=True, default='', max_length=264)),
                ('driver_pan_number', models.CharField(blank=True, default='', max_length=264)),
                ('driver_address_proof', models.CharField(blank=True, default='', max_length=264)),
                ('driver_photoid_proof', models.CharField(blank=True, default='', max_length=264)),
                ('driver_driver_bank_name', models.CharField(default='', max_length=264)),
                ('driver_bank_name', models.CharField(blank=True, default='', max_length=264)),
                ('driver_bank_account_number', models.CharField(blank=True, max_length=264)),
                ('driver_ban_ifsc_code', models.CharField(blank=True, default='', max_length=264)),
                ('driver_bank_branch', models.CharField(blank=True, default='', max_length=264)),
                ('driver_alternate_contact_number', models.CharField(blank=True, default='', max_length=264)),
                ('driver_license_residence_address', models.CharField(blank=True, default='', max_length=264)),
                ('driver_aadhar_card_residence_address', models.CharField(blank=True, default='', max_length=264)),
                ('driver_years_of_experience', models.CharField(blank=True, default='', max_length=264)),
                ('driver_last_employer_name', models.CharField(blank=True, default='', max_length=264)),
                ('driver_profile_image', models.ImageField(blank=True, null=True, upload_to='driver_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_by', models.CharField(max_length=264)),
                ('Review_To', models.CharField(max_length=264)),
                ('Review_Message', models.CharField(max_length=500)),
                ('Review_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
